{% set version = '2.0-36' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lmertest
  version: {{ version|replace("-", "_") }}

source:
  fn: lmerTest_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/lmerTest_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/lmerTest/lmerTest_{{ version }}.tar.gz
  sha256: 178717ce9dbfa54d11f0ed320759ddd231b9c7cce4d9cf712faa3757883745c9


  # patches:
   # List any patch files here
   # - fix.patch

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: pbkrtest, nlme, estimability
requirements:
  build:

  host:
    - r-base
    - r-hmisc
    - r-mass
    - r-matrix
    - r-ggplot2
    - r-lme4 >=1.0
    - r-plyr

  run:
    - r-base
    - r-hmisc
    - r-mass
    - r-matrix
    - r-ggplot2
    - r-lme4 >=1.0
    - r-plyr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('lmerTest')"           # [not win]
    - "\"%R%\" -e \"library('lmerTest')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=lmerTest
  license: GPL (>= 2)
  summary: Different kinds of tests for linear mixed effects models as implemented in 'lme4'
    package are provided. The tests comprise types I - III F tests for fixed effects,
    LR tests for random effects. The package also provides the calculation of population
    means for fixed factors with confidence intervals  and corresponding plots. Finally
    the backward elimination of non-significant effects is implemented.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: lmerTest
# Type: Package
# Title: Tests in Linear Mixed Effects Models
# Version: 2.0-36
# Authors@R: c(person("Alexandra", "Kuznetsova", role = c("aut")), person("Per", "Bruun Brockhoff", role = c("aut", "ths", "cre"), email = "perbb@dtu.dk"), person("Rune", "Haubo Bojesen Christensen", role =  c("aut"), email = "Rune@ChristensenStatistics.dk"))
# Depends: R (>= 3.0.0), Matrix, stats, methods, lme4 (>= 1.0)
# Imports: plyr, MASS, Hmisc, ggplot2
# Suggests: pbkrtest, nlme, estimability
# Description: Different kinds of tests for linear mixed effects models as implemented in 'lme4' package are provided. The tests comprise types I - III F tests for fixed effects, LR tests for random effects. The package also provides the calculation of population means for fixed factors with confidence intervals  and corresponding plots. Finally the backward elimination of non-significant effects is implemented.
# LazyData: TRUE
# License: GPL (>= 2)
# NeedsCompilation: no
# Packaged: 2017-11-29 20:49:20 UTC; rhbc
# Author: Alexandra Kuznetsova [aut], Per Bruun Brockhoff [aut, ths, cre], Rune Haubo Bojesen Christensen [aut]
# Maintainer: Per Bruun Brockhoff <perbb@dtu.dk>
# Repository: CRAN
# Date/Publication: 2017-11-30 13:00:11 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
