travis:
  secure:
    BINSTAR_TOKEN: Rq3IDkYC+cO/mDwyuaqyckIIBBK8kw8QlYw27gP4UyvWTkMUSWgAMr8V+ZhzLs4T33MFtGcv20eBN/XpHtJ9+AbSPvDSmkOEkHgBInhhTChWast4T4Ssx6ORf7Q7tsn5PWGt60pFKWP5Fcyw9vC+qc7FdzY7R0DXg88mYMgHJz56DEw83PR/bZs7u3HVSyfxMK2HZZPXUVJU1mRpfqMm851LjJR9CZWZwU41PSoBsXPU5zS7MPxG9p3AP5+FQTFmaSn6ftrL3JAtyWlmuBVDcbW2oNgPRDE1hdsKMUb9lVjb7MACQpCUzdXU69lTYILQDr363RC2IQUgsGQoog3wWk054XK4hcEYUZhmOlB+BgcAAvwH8up0k5Ny8d1OKzBYIAFcyh+ZrMgLD50KFMkcHL9UKT2o9QLztXfMxEBuPgNdHh9L8aFf8cE+Vqyf+qzSora9ShBc6zaG49uGJPhCy8zcsUhdT9JoChgfrCQMdsUCfy+Z7msOwW/sr2wLYkakW7DnjlVEs0oB0UAX5hS4CnMezRQuVJuRCcpWCIvGYLirAJr+6pPIgIAybZEvohTp2UjPJYOKGme9m5oREtQiqzbTzxHNrVtmJf/uMeBLe+IXGdYsJiaTb5m/M7Lcso6MJK3i6zwFlD09EvPndeSuYCuU+Y7uW1o4O/CCJC6/z40=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
